"""refresh_tokens replaced_by fk index

Revision ID: fdf435ab39d8
Revises: 313d4f534441
Create Date: 2026-08-22 21:16:40.508173
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fdf435ab39d8'
down_revision: str | Sequence[str] | None = '313d4f534441'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_refresh_tokens_replaced_by_id'), 'refresh_tokens', ['replaced_by_id'], unique=False)
    op.create_foreign_key(None, 'refresh_tokens', 'refresh_tokens', ['replaced_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_refresh_tokens_replaced_by_id'), table_name='refresh_tokens')
    # ### end Alembic commands ###
